Deploy the project
MeqdamAlqudah/Conference-page-project pull request #1
Opened 2021-11-17 12:21 UTC by MeqdamAlqudah

I will complete it later

2021-11-18 22:36 UTC, afanimartin requested changes
Hi @MeqdamAlqudah, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

### Martin Afani
#### Slack: whiz25

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-18 22:36 UTC, afanimartin commented on README.md
> +=======
- Please add "Acknowledgements" section to give credit to the UI design.

2021-11-18 22:36 UTC, afanimartin commented on dist/index .html
> +          >
### original design
![original-hero](https://user-images.githubusercontent.com/80149314/142506542-914eb32c-0f50-47c4-b2c7-e7c90e7c64db.jpg)

### your design
![review-hero](https://user-images.githubusercontent.com/80149314/142506855-3ad5bbc6-4017-43d3-95f7-210e4fb13b49.jpg)

Please make sure your deign looks the same as the given design. Your navbar,the dates and the text need some work. The font size should be big enough like in the given mockup.

2021-11-18 22:36 UTC, afanimartin commented on dist/index .html
> +        <p>2015 Creative Commons Korea Some Rights Reserved</p>
### original footer
![original-footer](https://user-images.githubusercontent.com/80149314/142507253-5f7b732f-3660-4867-af9f-dd00714eada9.jpg)
 Take note of the space between the logo and the text to the right, the two being centered. Also don't forget to give some margin. Please make the requested changes

2021-11-19 12:04 UTC, VanessaAoki requested changes
## STATUS: CHANGES REQUIRED :yellow_circle: 
Hi @MeqdamAlqudah, 

Great work on making the changes requested by the previous reviewer, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


![really close](https://c.tenor.com/fuKjtbt7b4EAAAAd/really-really-close-bill-murray.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-19 12:04 UTC, VanessaAoki commented on Css/queries.css
> +  }
- [ ] As requested by the previous reviewer, to make the header as similar to the Behance design, you could consider removing the `margin-bottom`, to make the elements horizontally centered.

2021-11-19 12:04 UTC, VanessaAoki commented on Css/style.css
> +  margin-top: 1rem;
- [ ] To match the original design better, you should make this horizontally centered.

Behance design:
![image](https://user-images.githubusercontent.com/66967274/142619745-08600f78-a44e-4f63-b044-a21add328224.png)

Your design:
![image](https://user-images.githubusercontent.com/66967274/142619854-83aa8ce7-1f65-4319-bb8b-d571781312db.png)

2021-11-19 12:29 UTC, carlos-ssh requested changes
# 🦺 🚧 🚥 CHANGES REQUIRED 🚥 🚧 🦺
#

Hi @MeqdamAlqudah , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._ 


![changesrequested](https://user-images.githubusercontent.com/22258274/139840240-ea0d564a-492a-44e3-87af-8d5830ab0d6d.gif)
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-19 12:29 UTC, carlos-ssh commented on index.html
> +        <p class="display-1">"Hello! Sharing world"</p>
**Kindly provide the requested design by the template:**

_**Template: **_
<img width="896" alt="Screen Shot 2021-11-19 at 6 19 30" src="https://user-images.githubusercontent.com/22258274/142622317-91c92926-cb40-41d4-92f3-9459b8f51abe.png">
<img width="1080" alt="Screen Shot 2021-11-19 at 6 18 50" src="https://user-images.githubusercontent.com/22258274/142622324-c21272d3-b182-4c40-a595-61e07904becf.png">
<img width="1080" alt="Screen Shot 2021-11-19 at 6 19 05" src="https://user-images.githubusercontent.com/22258274/142622326-7341e86a-34cc-468f-8c0a-835ba762ffea.png">

#
_**- Yours:**_
- Fix your fonts and style:
<img width="1440" alt="Screen Shot 2021-11-19 at 6 21 39" src="https://user-images.githubusercontent.com/22258274/142622536-ae60fd33-c3c2-4e09-8e67-cd577f8b6e0f.png">

- Fix image sizes:
<img width="1440" alt="Screen Shot 2021-11-19 at 6 25 02" src="https://user-images.githubusercontent.com/22258274/142622539-60b7eb42-b562-471c-94ec-8486d2f293b1.png">
- Align your footer items:
<img width="1440" alt="Screen Shot 2021-11-19 at 6 25 25" src="https://user-images.githubusercontent.com/22258274/142622543-aad1fc8f-52fe-4aac-a3fe-96f77fb382eb.png">


## Also kindly check your ``about.html``:

<img width="1440" alt="Screen Shot 2021-11-19 at 6 28 43" src="https://user-images.githubusercontent.com/22258274/142622915-bdd8c876-7a69-463a-8844-11bd13916186.png">

2021-11-19 13:29 UTC, carlos-ssh approved these changes
# 🍾🍾 **STATUS APPROVED** 👏🏽👏🏽

Hi @MeqdamAlqudah , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



![Approved](https://user-images.githubusercontent.com/22258274/138466108-6b14c541-6a88-44c5-ba76-c64992ac1835.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-19 13:31 UTC, merged

2021-11-19 16:43 UTC, bellom commented
Hello 👋,

This is an additional review as a result of the second opinion request.

Looks like the issue was resolved here, so I have nothing else to say other than best of luck with the rest of your projects!

Keep rocking 🚀!